name: Deploy Cloudflare Workers

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy-workers:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                worker:
                    - name: transcriptions
                      dir: apps/workers/transcriptions

        name: Deploy '${{ matrix.worker.name }}'
        steps:
            - uses: actions/checkout@v4

            - name: Deploy '${{ matrix.worker.name }}'
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  workingDirectory: ${{ matrix.worker.dir }}
                  wranglerVersion: "4.63.0"
